# Hexo Configuration
## Site
title: ABigRookie Blog
subtitle: ''
description: ''
keywords:
author: ABigRookie
language: zh-CN
timezone: Asia/Shanghai

## URL
url: https://abigrookie.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

## Directory
directory:
  posts: source/_posts

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
skip_render:

## Writing
new_post_name: :title.md
default_layout: post
auto_spacing: false
titlecase: false
external_link:
  enable: true
  field: site
  exclude:
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
time_format: YYYY-MM-DD
per_page: 10
pagination_dir: page

## Theme
theme: next

## Deployment
deploy:
  type: git
  repo: git@github.com:ABigRookie/ABigRookie.github.io.git
  branch: gh-pages
  message: Deploy at {now}

## Markdown-it options (enabled via hexo-renderer-markdown-it)
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: true
  anchors:
    level: 2
    collisionSuffix: ''
