menu:
  home: /
  categories: /categories/
  tags: /tags/
  archives: /archives/
  about: /about/

scheme: Muse

favicon:
  small: /favicon.ico
  medium: /favicon.ico
  apple_touch_icon: /favicon.ico

avatar:
  enabled: true
  url: /images/avatar.png
  rounded: true
  rotated: false

sidebar:
  position: left

social:
  GitHub: https://github.com/ABigRookie || fab fa-github
  Email: mailto:you@example.com || fa-solid fa-envelope

post_meta:
  updated_at:
    enable: true
